# Generated by Django 5.0 on 2024-12-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bairro",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="cep",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="user",
            name="cidade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="cnpj",
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="comprovante_endereco",
            field=models.FileField(blank=True, null=True, upload_to="comprovantes/"),
        ),
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="estado",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="user",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_usuarios/"),
        ),
    ]
