# Generated by Django 5.1.4 on 2025-01-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_bairro_user_cep_user_cidade_user_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, default='fotos_usuarios/avatar_padrao.png', null=True, upload_to='fotos_usuarios/'),
        ),
    ]
