# Generated by Django 5.1.4 on 2025-02-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categoria_imagem_local_categoria_url_imagem_externa'),
        ('users', '0006_alter_user_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, related_name='users_preferred', to='categories.categoria'),
        ),
    ]
