# Generated by Django 5.1.4 on 2025-03-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_preferred_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, help_text='Envie uma imagem quadrada para melhor visualização (recomendado 400x400px)', null=True, upload_to='fotos_usuarios/', verbose_name='Foto de perfil'),
        ),
    ]
