# Generated by Django 5.1.4 on 2025-04-25 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Use siglas como CE, SP, RJ …')]),
        ),
    ]
