# Generated by Django 5.1.10 on 2025-08-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_options_alter_user_bairro_alter_user_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Token de verificação'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True, verbose_name='E-mail verificado'),
        ),
    ]
