# Generated by Django 5.1.4 on 2025-01-14 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Necessidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('quantidade', models.FloatField()),
                ('medir_no_local', models.BooleanField(default=False)),
                ('unidade', models.CharField(help_text='Ex.: m², unidades, kg', max_length=50)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('bitola', models.IntegerField(blank=True, default=0.0, help_text='Ex.: Milímetros')),
                ('compr', models.IntegerField(blank=True, default=0.0, help_text='Ex.: Metros')),
                ('peso', models.IntegerField(blank=True, default=0.0, help_text='Ex.: Kilogramas')),
                ('altura', models.FloatField(blank=True, default=0.0, help_text='Ex.: Metros')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades', to='categories.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades', to=settings.AUTH_USER_MODEL)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades', to='categories.subcategoria')),
            ],
        ),
    ]
