# Generated by Django for State Machine implementation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),  # Update this to reference the actual last migration
    ]

    operations = [
        migrations.AddField(
            model_name='necessidade',
            name='data_primeiro_orcamento',
            field=models.DateTimeField(
                blank=True,
                help_text='Timestamp de quando o primeiro orçamento foi recebido',
                null=True,
                verbose_name='Data do primeiro orçamento'
            ),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='aguardando_confirmacao_desde',
            field=models.DateTimeField(
                blank=True,
                help_text='Timestamp de quando entrou no status aguardando_confirmacao (timeout de 48h)',
                null=True,
                verbose_name='Aguardando confirmação desde'
            ),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='data_finalizacao',
            field=models.DateTimeField(
                blank=True,
                help_text='Timestamp de quando a necessidade foi finalizada',
                null=True,
                verbose_name='Data de finalização'
            ),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='avaliacao_liberada',
            field=models.BooleanField(
                default=False,
                help_text='Se verdadeiro, permite avaliação entre cliente e fornecedor',
                verbose_name='Avaliação liberada'
            ),
        ),
    ]