# Generated by Django 5.1.4 on 2025-01-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessidade',
            name='duracao',
            field=models.DurationField(blank=True, help_text='Duração do serviço ou entrega (ex.: 7 dias, 3 horas)', null=True),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='ip_usuario',
            field=models.GenericIPAddressField(blank=True, help_text='Endereço IP do usuário que cadastrou o anúncio', null=True),
        ),
    ]
