# Generated by Django 5.1.4 on 2025-01-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_necessidade_duracao_necessidade_ip_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidade',
            name='duracao',
            field=models.CharField(blank=True, help_text='Duração do serviço ou entrega (ex.: 7 dias, 3 horas)', max_length=20, null=True),
        ),
    ]
