# Generated by Django 5.1.4 on 2025-01-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_necessidade_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessidade',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
