# Generated by Django 5.1.4 on 2025-02-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_necessidade_modificado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidade',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('em_andamento', 'Em andamento'), ('em_atendimento', 'Em atendimento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20),
        ),
    ]
