# Generated by Django 5.1.4 on 2025-03-03 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_necessidade_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='anuncios/%Y/%m/%d/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='ads.necessidade')),
            ],
            options={
                'verbose_name': 'Imagem do Anúncio',
                'verbose_name_plural': 'Imagens dos Anúncios',
                'ordering': ['-criado_em'],
            },
        ),
    ]
