# Generated by Django 5.1.4 on 2025-03-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_anuncioimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncioimagem',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
