# Generated by Django 5.1.4 on 2025-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_anuncioimagem_modificado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidade',
            name='bitola',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Ex.: Milímetros', max_digits=10),
        ),
        migrations.AlterField(
            model_name='necessidade',
            name='compr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Ex.: Metros', max_digits=10),
        ),
        migrations.AlterField(
            model_name='necessidade',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Ex.: Kilogramas', max_digits=10),
        ),
    ]
