# Generated by Django 5.1.10 on 2025-08-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_necessidade_bitola_alter_necessidade_compr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidade',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('analisando_orcamentos', 'Analisando orçamentos'), ('aguardando_confirmacao', 'Aguardando confirmação'), ('em_andamento', 'Em andamento'), ('em_atendimento', 'Em atendimento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='ativo', max_length=30),
        ),
    ]
