# Generated by Django 5.1.10 on 2025-08-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_adicionar_novos_estados_necessidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessidade',
            name='bairro_servico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro do serviço'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cep_servico',
            field=models.CharField(blank=True, help_text='Apenas números: 01234567', max_length=10, verbose_name='CEP do local do serviço'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cidade_servico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade do serviço'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='complemento_servico',
            field=models.CharField(blank=True, help_text='Apartamento, sala, etc.', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='endereco_completo_json',
            field=models.JSONField(blank=True, help_text='Dados retornados pela API de CEP/Geocoding', null=True, verbose_name='Dados completos do endereço'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='endereco_servico',
            field=models.CharField(blank=True, help_text='Rua, Avenida, etc.', max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='estado_servico',
            field=models.CharField(blank=True, help_text='Ex: SP, RJ, MG', max_length=2, verbose_name='Estado (UF) do serviço'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='lat_servico',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude do serviço'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='lon_servico',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude do serviço'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='numero_servico',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='usar_endereco_usuario',
            field=models.BooleanField(default=True, help_text='Marque se o serviço será executado no seu endereço cadastrado', verbose_name='Usar meu endereço'),
        ),
    ]
