# Generated by Django 5.1.10 on 2025-08-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_add_state_machine_fields'),
        ('ads', '0013_popular_endereco_servico_existentes'),
    ]

    operations = [
    ]
