# Generated by Django 5.1.10 on 2025-08-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_merge_20250816_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidade',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('analisando_orcamentos', 'Analisando orçamentos'), ('aguardando_confirmacao', 'Aguardando confirmação'), ('em_andamento', 'Em andamento'), ('em_atendimento', 'Em atendimento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado'), ('em_disputa', 'Em disputa')], default='ativo', max_length=30),
        ),
    ]
