# Generated by Django 5.1.10 on 2025-08-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_alter_necessidade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessidade',
            name='data_validade',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o anúncio expirará automaticamente. Se não informado, será definido automaticamente para 30 dias após a criação.', null=True, verbose_name='Data de validade'),
        ),
    ]
