# Generated by Django 5.1.10 on 2025-08-18 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_add_data_validade_to_necessidade'),
        ('budgets', '0013_alter_orcamento_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disputa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Descreva detalhadamente o problema ou conflito', verbose_name='Motivo da disputa')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em análise'), ('resolvida', 'Resolvida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status da disputa')),
                ('resolucao', models.TextField(blank=True, help_text='Resolução ou comentários do administrador', verbose_name='Resolução da disputa')),
                ('status_final_necessidade', models.CharField(blank=True, choices=[('em_atendimento', 'Voltar para Em Atendimento'), ('finalizado', 'Finalizar Necessidade'), ('cancelado', 'Cancelar Necessidade')], help_text='Para onde a necessidade deve ir após resolução da disputa', max_length=20, verbose_name='Status final da necessidade')),
                ('arquivo_evidencia', models.FileField(blank=True, help_text='Anexe arquivos que comprovem sua alegação (fotos, documentos, etc.)', null=True, upload_to='disputas/evidencias/%Y/%m/%d/', verbose_name='Arquivo de evidência')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de abertura')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de resolução')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('ip_usuario_abertura', models.GenericIPAddressField(blank=True, help_text='IP do usuário que abriu a disputa', null=True, verbose_name='IP do usuário')),
                ('comentarios_internos', models.TextField(blank=True, help_text='Comentários visíveis apenas para administradores', verbose_name='Comentários internos')),
                ('necessidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputas', to='ads.necessidade', verbose_name='Necessidade em disputa')),
                ('orcamento', models.ForeignKey(help_text='Orçamento que estava sendo executado quando a disputa foi aberta', on_delete=django.db.models.deletion.CASCADE, related_name='disputas', to='budgets.orcamento', verbose_name='Orçamento relacionado')),
                ('resolvida_por', models.ForeignKey(blank=True, help_text='Administrador que resolveu a disputa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputas_resolvidas', to=settings.AUTH_USER_MODEL, verbose_name='Resolvida por')),
                ('usuario_abertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputas_abertas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que abriu a disputa')),
            ],
            options={
                'verbose_name': 'Disputa',
                'verbose_name_plural': 'Disputas',
                'ordering': ['-data_abertura'],
                'indexes': [models.Index(fields=['status'], name='ads_disputa_status_7c2e99_idx'), models.Index(fields=['data_abertura'], name='ads_disputa_data_ab_cf9f11_idx'), models.Index(fields=['necessidade', 'status'], name='ads_disputa_necessi_4f3d4d_idx'), models.Index(fields=['usuario_abertura'], name='ads_disputa_usuario_845828_idx')],
            },
        ),
    ]
