# Generated by Django 5.1.10 on 2025-08-18 12:17

from django.db import migrations, models


def migrate_em_andamento_to_em_atendimento(apps, schema_editor):
    """
    Migra todos os registros com status 'em_andamento' para 'em_atendimento'.
    Como não existem dados com este status no banco, esta função é preventiva.
    """
    Necessidade = apps.get_model('ads', 'Necessidade')
    count_updated = Necessidade.objects.filter(status='em_andamento').update(status='em_atendimento')
    
    # Log para auditoria
    if count_updated > 0:
        print(f"Migrados {count_updated} registros de 'em_andamento' para 'em_atendimento'")
    else:
        print("Nenhum registro encontrado com status 'em_andamento' - migration executada com sucesso")


def reverse_migration(apps, schema_editor):
    """
    Reverso da migração - não implementado pois não queremos restaurar o status legacy
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_disputa'),
    ]

    operations = [
        # Primeiro migra os dados
        migrations.RunPython(
            migrate_em_andamento_to_em_atendimento, 
            reverse_migration
        ),
        
        # Depois atualiza as choices do modelo (sem o status em_andamento)
        migrations.AlterField(
            model_name='necessidade',
            name='status',
            field=models.CharField(
                choices=[
                    ('ativo', 'Ativo'),
                    ('analisando_orcamentos', 'Analisando orçamentos'),
                    ('aguardando_confirmacao', 'Aguardando confirmação'),
                    ('em_atendimento', 'Em atendimento'),
                    ('finalizado', 'Finalizado'),
                    ('cancelado', 'Cancelado'),
                    ('expirado', 'Expirado'),
                    ('em_disputa', 'Em disputa')
                ],
                default='ativo',
                max_length=30
            ),
        ),
    ]
