# Generated by Django 5.1.4 on 2025-05-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='estrelas',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='media_estrelas',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipo_avaliacao',
            field=models.CharField(choices=[('fornecedor', 'Fornecedor'), ('cliente', 'Cliente')], max_length=20),
        ),
        migrations.CreateModel(
            name='AvaliacaoCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(choices=[('rapidez_respostas', 'Rapidez nas respostas'), ('pagamento_acordado', 'Pagamento conforme acordado'), ('urbanidade_negociacao', 'Urbanidade na negociação'), ('qualidade_produto', 'Qualidade do Produto'), ('pontualidade_entrega', 'Pontualidade na entrega'), ('atendimento', 'Atendimento'), ('precos_mercado', 'Preços praticados de acordo com o Mercado')], max_length=30)),
                ('estrelas', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='rankings.avaliacao')),
            ],
            options={
                'verbose_name': 'Critério de Avaliação',
                'verbose_name_plural': 'Critérios de Avaliação',
                'unique_together': {('avaliacao', 'criterio')},
            },
        ),
    ]
