# Generated by Django 5.1.10 on 2025-08-18 20:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_remove_em_andamento_status'),
        ('rankings', '0002_alter_avaliacao_options_remove_avaliacao_estrelas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('usuario', 'anuncio', 'tipo_avaliacao')},
        ),
    ]
