# Generated by Django 5.1.4 on 2025-01-23 00:49

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem_local',
            field=models.ImageField(blank=True, help_text='Imagem carregada localmente', null=True, upload_to='categorias/', validators=[categories.models.validar_imagem]),
        ),
        migrations.AddField(
            model_name='categoria',
            name='url_imagem_externa',
            field=models.URLField(blank=True, help_text='URL de uma imagem externa', null=True),
        ),
    ]
