# Generated by Django 5.1.4 on 2025-04-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categoria_imagem_local_categoria_url_imagem_externa'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, help_text="Classe do ícone do Font Awesome (ex: 'fas fa-wrench')", max_length=50),
        ),
    ]
