
from django.core.management.base import BaseCommand
from categories.models import SubCategoria  

descricao_dict = {
    'Estrutura de concreto armado': 'Estrutura ou material feito com concreto armado ou pré-moldado.',
    'Estrutura de madeira': 'Estrutura ou revestimento utilizando madeira tratada.',
    'Redes de distribuição de água': 'Sistema ou equipamento relacionado à distribuição ou uso de água.',
    'Redes de esgoto e drenagem': 'Sistema de tubulações e drenagem de águas pluviais e esgoto.',
    'Bombas e pressurizadores': 'Equipamentos de bombeamento e pressurização de água.',
    'Sistemas de automação residencial': 'Sistemas de automação residencial ou predial.',
    'Cabeamento e fios elétricos': 'Instalação de cabeamentos e fios elétricos.',
    'Refrigeração evaporativa': 'Sistemas de ventilação e refrigeração para ambientes.',
    'Equipamentos de proteção individual (EPIs)': 'Equipamentos de proteção individual (EPIs) para segurança.',
    'Treinamento e conscientização': 'Atividades de treinamento e conscientização em segurança.',
    'Projetos de instalações elétricas e hidráulicas': 'Serviços de elaboração e consultoria de projetos técnicos.',
    'Rodovias e pavimentação': 'Subcategoria relacionada a rodovias e pavimentação.',
    'Pontes e viadutos': 'Subcategoria relacionada a pontes e viadutos.',
    'Obras de drenagem e contenção de encostas': 'Sistema de tubulações e drenagem de águas pluviais e esgoto.',
    'Radier e sapatas': 'Soluções de fundação e estruturas de suporte do solo.',
    'Fundos impermeabilizados': 'Subcategoria relacionada a fundos impermeabilizados.',
    'Reformas residenciais': 'Subcategoria relacionada a reformas residenciais.',
    'Manutenção de fachadas': 'Subcategoria relacionada a manutenção de fachadas.',
    'Reparos de telhados e coberturas': 'Subcategoria relacionada a reparos de telhados e coberturas.',
    'Manutenção de sistemas elétricos e hidráulicos': 'Subcategoria relacionada a manutenção de sistemas elétricos e hidráulicos.',
    'Restauro de patrimônio histórico': 'Subcategoria relacionada a restauro de patrimônio histórico.',
    'Planejamento e cronograma': 'Subcategoria relacionada a planejamento e cronograma.',
    'Controle de qualidade': 'Subcategoria relacionada a controle de qualidade.',
    'Gestão de equipe e mão de obra': 'Subcategoria relacionada a gestão de equipe e mão de obra.',
    'Acompanhamento de obras': 'Subcategoria relacionada a acompanhamento de obras.',
    'Custos e orçamento de obras': 'Subcategoria relacionada a custos e orçamento de obras.',
    'Transporte de materiais pesados': 'Subcategoria relacionada a transporte de materiais pesados.',
    'Frota de caminhões e veículos pesados': 'Subcategoria relacionada a frota de caminhões e veículos pesados.',
    'Planejamento logístico de obras': 'Subcategoria relacionada a planejamento logístico de obras.',
    'Locção de guindastes e plataformas': 'Subcategoria relacionada a locção de guindastes e plataformas.',
    'Concreto de baixo carbono': 'Estrutura ou material feito com concreto armado ou pré-moldado.',
    'Telhas solares e vidros fotovoltaicos': 'Subcategoria relacionada a telhas solares e vidros fotovoltaicos.',
    'Construção modular e pré-fabricada': 'Subcategoria relacionada a construção modular e pré-fabricada.',
    'Impressão 3D de estruturas': 'Componentes estruturais de uma edificação.',
    'Drones e tecnologias de monitoramento': 'Subcategoria relacionada a drones e tecnologias de monitoramento.',
    'Modelagem 3D e BIM (Building Information Modeling)': 'Subcategoria relacionada a modelagem 3d e bim (building information modeling).',
    'IoT (Internet das Coisas) em construções inteligentes': 'Subcategoria relacionada a iot (internet das coisas) em construções inteligentes.',
    'Painéis solares fotovoltaicos': 'Subcategoria relacionada a painéis solares fotovoltaicos.',
    'Sistemas de aquecimento solar': 'Subcategoria relacionada a sistemas de aquecimento solar.',
    'Energia eólica (microturbinas)': 'Sistemas relacionados à geração ou distribuição de energia.',
    'Biomassa e biocombustíveis': 'Subcategoria relacionada a biomassa e biocombustíveis.',
    'Geotermia (aquecimento e resfriamento do solo)': 'Subcategoria relacionada a geotermia (aquecimento e resfriamento do solo).',
    'Irrigação automática': 'Subcategoria relacionada a irrigação automática.',
    'Instalação de sistemas de drenagem e impermeabilização': 'Sistema de tubulações e drenagem de águas pluviais e esgoto.',
    'Janelas e portas de vidro temperado': 'Subcategoria relacionada a janelas e portas de vidro temperado.',
    'Cortinas de vidro e sistemas de fachada': 'Subcategoria relacionada a cortinas de vidro e sistemas de fachada.',
    'Envidraçamento de sacadas': 'Subcategoria relacionada a envidraçamento de sacadas.',
    'Churrasqueiras e áreas gourmet': 'Subcategoria relacionada a churrasqueiras e áreas gourmet.',
    'Playground e áreas recreativas': 'Subcategoria relacionada a playground e áreas recreativas.',
    'Espaços para academias e fitness': 'Subcategoria relacionada a espaços para academias e fitness.',
    'Áreas de convivência e lounges': 'Subcategoria relacionada a áreas de convivência e lounges.',
    'Rampas e elevadores para deficientes': 'Subcategoria relacionada a rampas e elevadores para deficientes.',
    'Banheiros adaptados': 'Subcategoria relacionada a banheiros adaptados.',
    'Sinalização tátil e em braille': 'Subcategoria relacionada a sinalização tátil e em braille.',
    'Portas e corredores amplos': 'Subcategoria relacionada a portas e corredores amplos.',
    'Sistemas de alarme e câmeras de segurança': 'Sistemas e equipamentos de segurança em obras.',
    'Sensores de movimento e presença': 'Subcategoria relacionada a sensores de movimento e presença.',
    'Gerenciamento remoto (via aplicativo ou computador)': 'Subcategoria relacionada a gerenciamento remoto (via aplicativo ou computador).',
    'Revestimentos antichama': 'Aplicação de revestimentos e pintura em superfícies.',
    'Demolição manual e mecanizada': 'Serviços de demolição manual ou mecanizada.',
    'Desmonte de estruturas de concreto': 'Estrutura ou material feito com concreto armado ou pré-moldado.',
    'Recuperação de materiais recicláveis': 'Subcategoria relacionada a recuperação de materiais recicláveis.',
    'Descontaminação de terrenos': 'Subcategoria relacionada a descontaminação de terrenos.',
    'Gestão de resíduos de construção e demolição': 'Serviços de demolição manual ou mecanizada.',
    'Lojas e estabelecimentos comerciais': 'Subcategoria relacionada a lojas e estabelecimentos comerciais.',
    'Centros comerciais e shoppings': 'Subcategoria relacionada a centros comerciais e shoppings.',
    'Escritórios e andares corporativos': 'Subcategoria relacionada a escritórios e andares corporativos.',
    'Hotéis e pousadas': 'Subcategoria relacionada a hotéis e pousadas.',
    'Restaurantes e praças de alimentação': 'Subcategoria relacionada a restaurantes e praças de alimentação.',
    'Casas unifamiliares': 'Subcategoria relacionada a casas unifamiliares.',
    'Edifícios multifamiliares': 'Subcategoria relacionada a edifícios multifamiliares.',
    'Casas de luxo e personalizadas': 'Subcategoria relacionada a casas de luxo e personalizadas.',
    'Loteamentos e condomínios': 'Subcategoria relacionada a loteamentos e condomínios.',
    'Casas de baixo custo (habitação popular)': 'Subcategoria relacionada a casas de baixo custo (habitação popular).',
    'Ferrovias e metrôs': 'Subcategoria relacionada a ferrovias e metrôs.',
    'Aeroportos e heliportos': 'Subcategoria relacionada a aeroportos e heliportos.',
    'Portos e marinas': 'Subcategoria relacionada a portos e marinas.',
    'Ciclovias e calçadas': 'Subcategoria relacionada a ciclovias e calçadas.',
    'Parques urbanos e praças': 'Subcategoria relacionada a parques urbanos e praças.',
    'Requalificação de áreas deterioradas': 'Subcategoria relacionada a requalificação de áreas deterioradas.',
    'Análise de impacto ambiental': 'Subcategoria relacionada a análise de impacto ambiental.',
    'Licenciamento ambiental de obras': 'Subcategoria relacionada a licenciamento ambiental de obras.',
    'Soluções de gestão de resíduos': 'Subcategoria relacionada a soluções de gestão de resíduos.',
    'Recuperação de áreas degradadas': 'Subcategoria relacionada a recuperação de áreas degradadas.',
    'Gestão de recursos hídricos e energéticos': 'Subcategoria relacionada a gestão de recursos hídricos e energéticos.',
    'Manutenção de vias públicas': 'Subcategoria relacionada a manutenção de vias públicas.',
    'Manutenção de sistemas hidráulicos e de esgoto': 'Sistema de tubulações e drenagem de águas pluviais e esgoto.',
    'Manutenção de prédios comerciais e residenciais': 'Subcategoria relacionada a manutenção de prédios comerciais e residenciais.',
    'Manutenção de redes elétricas': 'Subcategoria relacionada a manutenção de redes elétricas.',
    'Manutenção de sistemas de drenagem': 'Sistema de tubulações e drenagem de águas pluviais e esgoto.',
    'Pintura e revestimento externo': 'Aplicação de revestimentos e pintura em superfícies.',
    'Fachadas ventiladas': 'Subcategoria relacionada a fachadas ventiladas.',
    'Revestimentos em pedras naturais': 'Aplicação de revestimentos e pintura em superfícies.',
    'Reaproveitamento de resíduos de construção': 'Subcategoria relacionada a reaproveitamento de resíduos de construção.',
    'Sistemas de compostagem e reciclagem': 'Subcategoria relacionada a sistemas de compostagem e reciclagem.',
    'Separação de resíduos': 'Subcategoria relacionada a separação de resíduos.',
    'Transporte de resíduos de construção': 'Subcategoria relacionada a transporte de resíduos de construção.',
    'Gestão de resíduos perigosos': 'Subcategoria relacionada a gestão de resíduos perigosos.',
    'Armazenamento e destinação final': 'Subcategoria relacionada a armazenamento e destinação final.',
    'Instalação de sistemas de fibra ótica': 'Subcategoria relacionada a instalação de sistemas de fibra ótica.',
    'Redes de telefonia e internet': 'Subcategoria relacionada a redes de telefonia e internet.',
    'Cabeamento estruturado': 'Instalação de cabeamentos e fios elétricos.',
    'Sistemas de antenas e transmissão': 'Subcategoria relacionada a sistemas de antenas e transmissão.',
    'Redes de comunicação para automação predial': 'Sistemas de automação residencial ou predial.',
    'Membranas asfálticas': 'Subcategoria relacionada a membranas asfálticas.',
    'Impermeabilização líquida': 'Subcategoria relacionada a impermeabilização líquida.',
    'Sistemas de barreira contra umidade': 'Subcategoria relacionada a sistemas de barreira contra umidade.',
    'Sistemas para telhados e lajes': 'Subcategoria relacionada a sistemas para telhados e lajes.',
    'Impermeabilização de fundações': 'Subcategoria relacionada a impermeabilização de fundações.',
    'Jardins verticais internos': 'Subcategoria relacionada a jardins verticais internos.',
    'Sistemas de irrigação vertical': 'Subcategoria relacionada a sistemas de irrigação vertical.',
    'Plantas e vegetação para fachadas': 'Subcategoria relacionada a plantas e vegetação para fachadas.',
    'Iluminação de jardins verticais': 'Sistema ou instalação de iluminação em ambientes.',
    'Sistemas de aquecimento a gás e elétrico': 'Subcategoria relacionada a sistemas de aquecimento a gás e elétrico.',
    'Ventiladores industriais': 'Subcategoria relacionada a ventiladores industriais.',
    'Aquecimento solar de água': 'Sistema ou equipamento relacionado à distribuição ou uso de água.',
    'Sistemas de ventilação natural': 'Sistemas de ventilação e refrigeração para ambientes.',
    'Ar condicionado central e split': 'Subcategoria relacionada a ar condicionado central e split.',
    'Recuperação de concreto': 'Estrutura ou material feito com concreto armado ou pré-moldado.',
    'Reforço estrutural': 'Componentes estruturais de uma edificação.',
    'Reparo de fundações e estacas': 'Soluções de fundação e estruturas de suporte do solo.',
    'Reabilitação de estruturas metálicas': 'Componentes estruturais de uma edificação.',
    'Proteção contra corrosão': 'Equipamentos de proteção individual (EPIs) para segurança.',
    'Fábricas e instalações industriais': 'Subcategoria relacionada a fábricas e instalações industriais.',
    'Galpões comerciais e logísticos': 'Subcategoria relacionada a galpões comerciais e logísticos.',
    'Armazéns e centros de distribuição': 'Subcategoria relacionada a armazéns e centros de distribuição.',
    'Construção de usinas': 'Subcategoria relacionada a construção de usinas.',
    'Construção de instalações de mineração': 'Subcategoria relacionada a construção de instalações de mineração.',
    'Planejamento de projetos': 'Serviços de elaboração e consultoria de projetos técnicos.',
    'Cronograma de obras': 'Subcategoria relacionada a cronograma de obras.',
    'Gestão de risco em obras': 'Subcategoria relacionada a gestão de risco em obras.',
    'Monitoramento de andamento': 'Subcategoria relacionada a monitoramento de andamento.',
    'Análise de custo-benefício': 'Subcategoria relacionada a análise de custo-benefício.',
    'Estudos de viabilidade': 'Subcategoria relacionada a estudos de viabilidade.',
    'Análise de impacto urbano': 'Subcategoria relacionada a análise de impacto urbano.',
    'Planejamento estratégico de obras': 'Subcategoria relacionada a planejamento estratégico de obras.',
    'Elaboração de cronogramas': 'Subcategoria relacionada a elaboração de cronogramas.',
    'Gerenciamento de recursos': 'Subcategoria relacionada a gerenciamento de recursos.',
    'Casinhas modulares': 'Subcategoria relacionada a casinhas modulares.',
    'Estruturas modulares': 'Componentes estruturais de uma edificação.',
    'Painéis pré-fabricados': 'Subcategoria relacionada a painéis pré-fabricados.',
    'Construção de casas temporárias': 'Subcategoria relacionada a construção de casas temporárias.',
    'Unidades habitacionais modulares': 'Subcategoria relacionada a unidades habitacionais modulares.',
    'Infraestrutura conectada': 'Componentes estruturais de uma edificação.',
    'Monitoramento urbano (sensores)': 'Subcategoria relacionada a monitoramento urbano (sensores).',
    'Gestão de resíduos inteligente': 'Subcategoria relacionada a gestão de resíduos inteligente.',
    'Iluminação pública eficiente': 'Sistema ou instalação de iluminação em ambientes.',
    'Mobilidade urbana inteligente': 'Subcategoria relacionada a mobilidade urbana inteligente.',
    'Sistemas de sprinklers': 'Subcategoria relacionada a sistemas de sprinklers.',
    'Extintores e mangueiras': 'Subcategoria relacionada a extintores e mangueiras.',
    'Sinalização de emergência': 'Subcategoria relacionada a sinalização de emergência.',
    'Treinamento de brigadistas': 'Atividades de treinamento e conscientização em segurança.',
    'Sistemas de alarme e detecção': 'Subcategoria relacionada a sistemas de alarme e detecção.',
    'Instalação de painéis solares': 'Subcategoria relacionada a instalação de painéis solares.',
    'Gerenciamento de energia': 'Sistemas relacionados à geração ou distribuição de energia.',
    'Armazenamento de energia (baterias)': 'Sistemas relacionados à geração ou distribuição de energia.',
    'Energia solar fotovoltaica': 'Sistemas relacionados à geração ou distribuição de energia.',
    'Lojas e franquias': 'Subcategoria relacionada a lojas e franquias.',
    'Escritórios comerciais': 'Subcategoria relacionada a escritórios comerciais.',
    'Salas comerciais': 'Subcategoria relacionada a salas comerciais.',
    'Galerias e centros comerciais': 'Subcategoria relacionada a galerias e centros comerciais.',
    'Showrooms e estúdios': 'Subcategoria relacionada a showrooms e estúdios.',
    'Hospitais e clínicas': 'Subcategoria relacionada a hospitais e clínicas.',
    'Unidades de pronto atendimento (UPAs)': 'Subcategoria relacionada a unidades de pronto atendimento (upas).',
    'Laboratórios e farmácias': 'Subcategoria relacionada a laboratórios e farmácias.',
    'Ambulatórios e consultórios': 'Subcategoria relacionada a ambulatórios e consultórios.',
    'Centros de reabilitação': 'Subcategoria relacionada a centros de reabilitação.',
    'Escolas públicas e privadas': 'Subcategoria relacionada a escolas públicas e privadas.',
    'Universidades e campi': 'Subcategoria relacionada a universidades e campi.',
    'Centros de educação infantil': 'Subcategoria relacionada a centros de educação infantil.',
    'Quadras e ginásios': 'Subcategoria relacionada a quadras e ginásios.',
    'Instalações de recreação escolar': 'Subcategoria relacionada a instalações de recreação escolar.',
    'Planejamento de redes de transporte': 'Subcategoria relacionada a planejamento de redes de transporte.',
    'Gestão de sistemas urbanos': 'Subcategoria relacionada a gestão de sistemas urbanos.',
    'Desenvolvimento de infraestrutura': 'Componentes estruturais de uma edificação.',
    'Operação e manutenção de redes públicas': 'Subcategoria relacionada a operação e manutenção de redes públicas.',
    'Monitoramento e controle de infraestrutura': 'Componentes estruturais de uma edificação.',

}

class Command(BaseCommand):
    help = 'Atualiza as descrições curtas das subcategorias no banco de dados'

    def handle(self, *args, **options):
        total_atualizadas = 0
        total_nao_encontradas = 0

        for nome, descricao in descricao_dict.items():
            subcategorias = SubCategoria.objects.filter(nome=nome)
            count = subcategorias.update(descricao=descricao)

            if count:
                total_atualizadas += count
                self.stdout.write(self.style.SUCCESS(f'Descrição atualizada para {count} registro(s): {nome}'))
            else:
                total_nao_encontradas += 1
                self.stdout.write(self.style.WARNING(f'Subcategoria não encontrada: {nome}'))

        self.stdout.write(self.style.SUCCESS(f'\nTotal de subcategorias atualizadas: {total_atualizadas}'))
        self.stdout.write(self.style.WARNING(f'Total de subcategorias não encontradas: {total_nao_encontradas}'))
