# Generated by Django 5.1.4 on 2025-01-19 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do anúncio')),
                ('quantidade', models.FloatField()),
                ('unidade', models.CharField(max_length=50)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo_validade', models.DateField()),
                ('prazo_entrega', models.DateField()),
                ('arquivo_anexo', models.FileField(blank=True, null=True, upload_to='orcamentos_anexos/')),
                ('observacao', models.TextField(blank=True, help_text='Comentários adicionais sobre o orçamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='ads.necessidade')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
