# Generated by Django 5.1.4 on 2025-01-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='descricao',
            field=models.TextField(blank='True'),
        ),
    ]
