# Generated by Django 5.1.4 on 2025-01-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_orcamento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
