# Generated by Django 5.1.4 on 2025-06-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_novo_modelo_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
