# Generated by Django 5.1.10 on 2025-08-17 00:29

from django.db import migrations, models


def update_orcamento_status_values(apps, schema_editor):
    """
    Atualiza os valores de status existentes para os novos valores de negócio:
    - 'pendente' -> 'enviado'
    - 'rejeitado' -> 'rejeitado_pelo_cliente' 
    - Remove 'aceito_pelo_fornecedor' (não usado nas novas regras)
    """
    Orcamento = apps.get_model('budgets', 'Orcamento')
    
    # Atualizar pendente para enviado
    pendentes_count = Orcamento.objects.filter(status='pendente').count()
    if pendentes_count > 0:
        Orcamento.objects.filter(status='pendente').update(status='enviado')
        print(f"✓ Atualizados {pendentes_count} orçamentos de 'pendente' para 'enviado'")
    
    # Atualizar rejeitado genérico para rejeitado_pelo_cliente
    rejeitados_count = Orcamento.objects.filter(status='rejeitado').count()
    if rejeitados_count > 0:
        Orcamento.objects.filter(status='rejeitado').update(status='rejeitado_pelo_cliente')
        print(f"✓ Atualizados {rejeitados_count} orçamentos de 'rejeitado' para 'rejeitado_pelo_cliente'")
    
    # Verificar se há orçamentos com aceito_pelo_fornecedor (deve ser muito raro)
    aceitos_fornecedor_count = Orcamento.objects.filter(status='aceito_pelo_fornecedor').count()
    if aceitos_fornecedor_count > 0:
        # Estes orçamentos ficam como 'confirmado' já que representam acordos fechados
        Orcamento.objects.filter(status='aceito_pelo_fornecedor').update(status='confirmado')
        print(f"⚠️  Convertidos {aceitos_fornecedor_count} orçamentos 'aceito_pelo_fornecedor' para 'confirmado'")


def reverse_orcamento_status_values(apps, schema_editor):
    """
    Reverte as alterações de status para os valores antigos
    """
    Orcamento = apps.get_model('budgets', 'Orcamento')
    
    # Reverter enviado para pendente
    Orcamento.objects.filter(status='enviado').update(status='pendente')
    
    # Reverter rejeitado_pelo_cliente para rejeitado
    Orcamento.objects.filter(status='rejeitado_pelo_cliente').update(status='rejeitado_pelo_cliente')


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_drop_valor_column'),
    ]

    operations = [
        # Primeiro, atualizar os dados existentes
        migrations.RunPython(
            update_orcamento_status_values,
            reverse_orcamento_status_values,
        ),
        # Depois, alterar as choices do campo
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('aceito_pelo_cliente', 'Aceito pelo cliente'), ('confirmado', 'Confirmado'), ('rejeitado_pelo_cliente', 'Rejeitado pelo cliente'), ('recusado_pelo_fornecedor', 'Recusado pelo fornecedor')], default='enviado', max_length=50),
        ),
    ]
