# Generated by Django 5.1.10 on 2025-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0012_update_orcamento_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('aceito_pelo_cliente', 'Aceito pelo cliente'), ('confirmado', 'Confirmado'), ('rejeitado_pelo_cliente', 'Rejeitado pelo cliente'), ('recusado_pelo_fornecedor', 'Recusado pelo fornecedor'), ('cancelado_pelo_fornecedor', 'Cancelado pelo fornecedor'), ('finalizado', 'Finalizado'), ('anuncio_cancelado', 'Anúncio cancelado'), ('anuncio_expirado', 'Anúncio expirado')], default='enviado', max_length=50),
        ),
    ]
