# Generated by Django 5.1.4 on 2025-03-21 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_anuncioimagem_modificado_em'),
        ('notifications', '0002_alter_notification_options_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='necessidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.necessidade'),
        ),
    ]
