# Generated by Django 5.1.4 on 2025-05-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_necessidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_AD', 'Novo Anúncio'), ('NEW_END_AD', 'Anúncio Finalizado'), ('NEW_BUDGET', 'Novo Orçamento'), ('BUDGET_REJECTED', 'Orçamento Rejeitado'), ('NEW_AVALIACAO', 'Nova Avaliação')], default='NEW_AD', max_length=20),
        ),
    ]
