# Generated by Django 5.1.10 on 2025-08-17 01:18

from django.db import migrations, models


def populate_titles(apps, schema_editor):
    """Populate title field based on notification_type."""
    Notification = apps.get_model('notifications', 'Notification')
    
    type_title_mapping = {
        'NEW_AD': 'Nova Necessidade Criada',
        'NEW_END_AD': 'Necessidade Finalizada',
        'AD_CANCELLED': 'Necessidade Cancelada',
        'NECESSIDADE_EXPIRADA': 'Necessidade Expirada',
        'NEW_BUDGET': 'Novo Orçamento Recebido',
        'NOVO_ORCAMENTO': 'Orçamento Enviado',
        'BUDGET_ACCEPTED': 'Orçamento Aceito pelo Cliente',
        'ORCAMENTO_ACEITO': 'Seu Orçamento foi Aceito',
        'BUDGET_CONFIRMED': 'Orçamento Confirmado pelo Fornecedor',
        'ORCAMENTO_CONFIRMADO': 'Orçamento Confirmado',
        'BUDGET_REFUSED': 'Orçamento Recusado',
        'ORCAMENTO_REJEITADO': 'Orçamento Rejeitado',
        'ORCAMENTO_RECUSADO': 'Orçamento Recusado pelo Fornecedor',
        'SERVICE_STARTED': 'Serviço Iniciado',
        'SERVICE_COMPLETED': 'Serviço Finalizado',
        'AVALIACAO_LIBERADA': 'Avaliação Liberada',
        'TIMEOUT_WARNING': 'Aviso de Timeout',
        'CONFIRMATION_TIMEOUT': 'Timeout de Confirmação',
        'SYSTEM_MESSAGE': 'Mensagem do Sistema',
        'WELCOME': 'Bem-vindo',
        'ACCOUNT_VERIFIED': 'Conta Verificada',
    }
    
    for notification in Notification.objects.all():
        title = type_title_mapping.get(notification.notification_type, 'Notificação')
        notification.title = title
        notification.save(update_fields=['title'])


def reverse_populate_titles(apps, schema_editor):
    """Reverse operation - not needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_necessidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notificação', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_titles, reverse_populate_titles),
    ]
