# Generated by Django 5.1.10 on 2025-08-17 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_merge_20250816_2217'),
        ('budgets', '0012_update_orcamento_status_choices'),
        ('notifications', '0004_auto_20250816_2218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('notification_type', models.CharField(choices=[('NEW_AD', 'Nova Necessidade Criada'), ('NEW_END_AD', 'Necessidade Finalizada'), ('AD_CANCELLED', 'Necessidade Cancelada'), ('NECESSIDADE_EXPIRADA', 'Necessidade Expirada'), ('NEW_BUDGET', 'Novo Orçamento Recebido'), ('NOVO_ORCAMENTO', 'Orçamento Enviado'), ('BUDGET_ACCEPTED', 'Orçamento Aceito pelo Cliente'), ('ORCAMENTO_ACEITO', 'Seu Orçamento foi Aceito'), ('BUDGET_CONFIRMED', 'Orçamento Confirmado pelo Fornecedor'), ('ORCAMENTO_CONFIRMADO', 'Orçamento Confirmado'), ('BUDGET_REFUSED', 'Orçamento Recusado'), ('ORCAMENTO_REJEITADO', 'Orçamento Rejeitado'), ('ORCAMENTO_RECUSADO', 'Orçamento Recusado pelo Fornecedor'), ('SERVICE_STARTED', 'Serviço Iniciado'), ('SERVICE_COMPLETED', 'Serviço Finalizado'), ('AVALIACAO_LIBERADA', 'Avaliação Liberada'), ('TIMEOUT_WARNING', 'Aviso de Timeout'), ('CONFIRMATION_TIMEOUT', 'Timeout de Confirmação'), ('SYSTEM_MESSAGE', 'Mensagem do Sistema'), ('WELCOME', 'Bem-vindo'), ('ACCOUNT_VERIFIED', 'Conta Verificada')], max_length=30, verbose_name='Tipo de Notificação')),
                ('target_criteria', models.JSONField(blank=True, default=dict, help_text='Critérios para seleção automática de usuários', verbose_name='Critérios de alvo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='draft', max_length=20, verbose_name='Status')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('total_notifications', models.PositiveIntegerField(default=0, verbose_name='Total de notificações')),
                ('successful_notifications', models.PositiveIntegerField(default=0, verbose_name='Notificações enviadas')),
                ('failed_notifications', models.PositiveIntegerField(default=0, verbose_name='Notificações falharam')),
            ],
            options={
                'verbose_name': 'Lote de Notificações',
                'verbose_name_plural': 'Lotes de Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('in_app', 'No Aplicativo'), ('email', 'E-mail'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20, verbose_name='Método de entrega')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('bounced', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Tentativa em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('external_id', models.CharField(blank=True, max_length=200, verbose_name='ID externo')),
                ('external_response', models.JSONField(blank=True, default=dict, verbose_name='Resposta externa')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_AD', 'Nova Necessidade Criada'), ('NEW_END_AD', 'Necessidade Finalizada'), ('AD_CANCELLED', 'Necessidade Cancelada'), ('NECESSIDADE_EXPIRADA', 'Necessidade Expirada'), ('NEW_BUDGET', 'Novo Orçamento Recebido'), ('NOVO_ORCAMENTO', 'Orçamento Enviado'), ('BUDGET_ACCEPTED', 'Orçamento Aceito pelo Cliente'), ('ORCAMENTO_ACEITO', 'Seu Orçamento foi Aceito'), ('BUDGET_CONFIRMED', 'Orçamento Confirmado pelo Fornecedor'), ('ORCAMENTO_CONFIRMADO', 'Orçamento Confirmado'), ('BUDGET_REFUSED', 'Orçamento Recusado'), ('ORCAMENTO_REJEITADO', 'Orçamento Rejeitado'), ('ORCAMENTO_RECUSADO', 'Orçamento Recusado pelo Fornecedor'), ('SERVICE_STARTED', 'Serviço Iniciado'), ('SERVICE_COMPLETED', 'Serviço Finalizado'), ('AVALIACAO_LIBERADA', 'Avaliação Liberada'), ('TIMEOUT_WARNING', 'Aviso de Timeout'), ('CONFIRMATION_TIMEOUT', 'Timeout de Confirmação'), ('SYSTEM_MESSAGE', 'Mensagem do Sistema'), ('WELCOME', 'Bem-vindo'), ('ACCOUNT_VERIFIED', 'Conta Verificada')], max_length=30, unique=True, verbose_name='Tipo de Notificação')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('html_content', models.TextField(verbose_name='Conteúdo HTML')),
                ('text_content', models.TextField(blank=True, verbose_name='Conteúdo Texto')),
                ('available_variables', models.TextField(blank=True, help_text='Documentação das variáveis disponíveis no template', verbose_name='Variáveis Disponíveis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Notificações habilitadas')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='E-mail habilitado')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='Notificações no app habilitadas')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS habilitado')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push notifications habilitadas')),
                ('instant_notifications', models.BooleanField(default=True, verbose_name='Notificações instantâneas')),
                ('daily_digest', models.BooleanField(default=False, verbose_name='Resumo diário')),
                ('weekly_digest', models.BooleanField(default=False, verbose_name='Resumo semanal')),
                ('new_budget_notifications', models.BooleanField(default=True, verbose_name='Novos orçamentos')),
                ('budget_status_notifications', models.BooleanField(default=True, verbose_name='Status de orçamentos')),
                ('service_notifications', models.BooleanField(default=True, verbose_name='Notificações de serviço')),
                ('timeout_warnings', models.BooleanField(default=True, verbose_name='Avisos de timeout')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='Notificações do sistema')),
                ('marketing_notifications', models.BooleanField(default=False, verbose_name='Notificações de marketing')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='Horário silencioso habilitado')),
                ('quiet_start_time', models.TimeField(blank=True, null=True, verbose_name='Início do horário silencioso')),
                ('quiet_end_time', models.TimeField(blank=True, null=True, verbose_name='Fim do horário silencioso')),
                ('timezone', models.CharField(default='America/Sao_Paulo', help_text='Fuso horário para controle de horário silencioso', max_length=50, verbose_name='Fuso horário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Preferências de Notificação',
                'verbose_name_plural': 'Preferências de Notificações',
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
        migrations.AddField(
            model_name='notification',
            name='action_taken',
            field=models.BooleanField(default=False, verbose_name='Ação realizada'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ação realizada em'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, verbose_name='URL da ação'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_error',
            field=models.TextField(blank=True, verbose_name='Erro no e-mail'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='E-mail enviado'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em'),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadados'),
        ),
        migrations.AddField(
            model_name='notification',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.orcamento', verbose_name='Orçamento'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lida em'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criada em'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lida'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='necessidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.necessidade', verbose_name='Necessidade'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_AD', 'Nova Necessidade Criada'), ('NEW_END_AD', 'Necessidade Finalizada'), ('AD_CANCELLED', 'Necessidade Cancelada'), ('NECESSIDADE_EXPIRADA', 'Necessidade Expirada'), ('NEW_BUDGET', 'Novo Orçamento Recebido'), ('NOVO_ORCAMENTO', 'Orçamento Enviado'), ('BUDGET_ACCEPTED', 'Orçamento Aceito pelo Cliente'), ('ORCAMENTO_ACEITO', 'Seu Orçamento foi Aceito'), ('BUDGET_CONFIRMED', 'Orçamento Confirmado pelo Fornecedor'), ('ORCAMENTO_CONFIRMADO', 'Orçamento Confirmado'), ('BUDGET_REFUSED', 'Orçamento Recusado'), ('ORCAMENTO_REJEITADO', 'Orçamento Rejeitado'), ('ORCAMENTO_RECUSADO', 'Orçamento Recusado pelo Fornecedor'), ('SERVICE_STARTED', 'Serviço Iniciado'), ('SERVICE_COMPLETED', 'Serviço Finalizado'), ('AVALIACAO_LIBERADA', 'Avaliação Liberada'), ('TIMEOUT_WARNING', 'Aviso de Timeout'), ('CONFIRMATION_TIMEOUT', 'Timeout de Confirmação'), ('SYSTEM_MESSAGE', 'Mensagem do Sistema'), ('WELCOME', 'Bem-vindo'), ('ACCOUNT_VERIFIED', 'Conta Verificada')], default='SYSTEM_MESSAGE', max_length=30, verbose_name='Tipo de Notificação'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='target_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários alvo'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification', verbose_name='Notificação'),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
