# Generated by Django 5.1.4 on 2025-06-30 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("notifications", "0004_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="chat_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chatroom",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_AD", "Novo Anúncio"),
                    ("NEW_END_AD", "Anúncio Finalizado"),
                    ("NEW_BUDGET", "Novo Orçamento"),
                    ("BUDGET_REJECTED", "Orçamento Rejeitado"),
                    ("NEW_AVALIACAO", "Nova Avaliação"),
                    ("NEW_CHAT_MESSAGE", "Nova Mensagem no Chat"),
                ],
                default="NEW_AD",
                max_length=20,
            ),
        ),
    ]
