# Generated by Django 5.1.10 on 2025-08-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='chat_notifications',
            field=models.BooleanField(default=True, verbose_name='Mensagens de chat'),
        ),
    ]
