# Generated by Django 5.1.10 on 2025-08-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_usernotificationpreferences_chat_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='dispute_notifications',
            field=models.BooleanField(default=True, verbose_name='Notificações de disputas'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_AD', 'Nova Necessidade Criada'), ('NEW_END_AD', 'Necessidade Finalizada'), ('AD_CANCELLED', 'Necessidade Cancelada'), ('NECESSIDADE_EXPIRADA', 'Necessidade Expirada'), ('NEW_BUDGET', 'Novo Orçamento Recebido'), ('NOVO_ORCAMENTO', 'Orçamento Enviado'), ('BUDGET_ACCEPTED', 'Orçamento Aceito pelo Cliente'), ('ORCAMENTO_ACEITO', 'Seu Orçamento foi Aceito'), ('BUDGET_CONFIRMED', 'Orçamento Confirmado pelo Fornecedor'), ('ORCAMENTO_CONFIRMADO', 'Orçamento Confirmado'), ('BUDGET_REFUSED', 'Orçamento Recusado'), ('ORCAMENTO_REJEITADO', 'Orçamento Rejeitado'), ('ORCAMENTO_RECUSADO', 'Orçamento Recusado pelo Fornecedor'), ('SERVICE_STARTED', 'Serviço Iniciado'), ('SERVICE_COMPLETED', 'Serviço Finalizado'), ('AVALIACAO_LIBERADA', 'Avaliação Liberada'), ('TIMEOUT_WARNING', 'Aviso de Timeout'), ('CONFIRMATION_TIMEOUT', 'Timeout de Confirmação'), ('NEW_CHAT_MESSAGE', 'Nova Mensagem no Chat'), ('DISPUTE_OPENED', 'Nova Disputa Aberta'), ('DISPUTE_RESOLVED', 'Disputa Resolvida'), ('DISPUTE_ADMIN_ALERT', 'Nova Disputa para Análise'), ('SYSTEM_MESSAGE', 'Mensagem do Sistema'), ('WELCOME', 'Bem-vindo'), ('ACCOUNT_VERIFIED', 'Conta Verificada')], default='SYSTEM_MESSAGE', max_length=30, verbose_name='Tipo de Notificação'),
        ),
        migrations.AlterField(
            model_name='notificationbatch',
            name='notification_type',
            field=models.CharField(choices=[('NEW_AD', 'Nova Necessidade Criada'), ('NEW_END_AD', 'Necessidade Finalizada'), ('AD_CANCELLED', 'Necessidade Cancelada'), ('NECESSIDADE_EXPIRADA', 'Necessidade Expirada'), ('NEW_BUDGET', 'Novo Orçamento Recebido'), ('NOVO_ORCAMENTO', 'Orçamento Enviado'), ('BUDGET_ACCEPTED', 'Orçamento Aceito pelo Cliente'), ('ORCAMENTO_ACEITO', 'Seu Orçamento foi Aceito'), ('BUDGET_CONFIRMED', 'Orçamento Confirmado pelo Fornecedor'), ('ORCAMENTO_CONFIRMADO', 'Orçamento Confirmado'), ('BUDGET_REFUSED', 'Orçamento Recusado'), ('ORCAMENTO_REJEITADO', 'Orçamento Rejeitado'), ('ORCAMENTO_RECUSADO', 'Orçamento Recusado pelo Fornecedor'), ('SERVICE_STARTED', 'Serviço Iniciado'), ('SERVICE_COMPLETED', 'Serviço Finalizado'), ('AVALIACAO_LIBERADA', 'Avaliação Liberada'), ('TIMEOUT_WARNING', 'Aviso de Timeout'), ('CONFIRMATION_TIMEOUT', 'Timeout de Confirmação'), ('NEW_CHAT_MESSAGE', 'Nova Mensagem no Chat'), ('DISPUTE_OPENED', 'Nova Disputa Aberta'), ('DISPUTE_RESOLVED', 'Disputa Resolvida'), ('DISPUTE_ADMIN_ALERT', 'Nova Disputa para Análise'), ('SYSTEM_MESSAGE', 'Mensagem do Sistema'), ('WELCOME', 'Bem-vindo'), ('ACCOUNT_VERIFIED', 'Conta Verificada')], max_length=30, verbose_name='Tipo de Notificação'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('NEW_AD', 'Nova Necessidade Criada'), ('NEW_END_AD', 'Necessidade Finalizada'), ('AD_CANCELLED', 'Necessidade Cancelada'), ('NECESSIDADE_EXPIRADA', 'Necessidade Expirada'), ('NEW_BUDGET', 'Novo Orçamento Recebido'), ('NOVO_ORCAMENTO', 'Orçamento Enviado'), ('BUDGET_ACCEPTED', 'Orçamento Aceito pelo Cliente'), ('ORCAMENTO_ACEITO', 'Seu Orçamento foi Aceito'), ('BUDGET_CONFIRMED', 'Orçamento Confirmado pelo Fornecedor'), ('ORCAMENTO_CONFIRMADO', 'Orçamento Confirmado'), ('BUDGET_REFUSED', 'Orçamento Recusado'), ('ORCAMENTO_REJEITADO', 'Orçamento Rejeitado'), ('ORCAMENTO_RECUSADO', 'Orçamento Recusado pelo Fornecedor'), ('SERVICE_STARTED', 'Serviço Iniciado'), ('SERVICE_COMPLETED', 'Serviço Finalizado'), ('AVALIACAO_LIBERADA', 'Avaliação Liberada'), ('TIMEOUT_WARNING', 'Aviso de Timeout'), ('CONFIRMATION_TIMEOUT', 'Timeout de Confirmação'), ('NEW_CHAT_MESSAGE', 'Nova Mensagem no Chat'), ('DISPUTE_OPENED', 'Nova Disputa Aberta'), ('DISPUTE_RESOLVED', 'Disputa Resolvida'), ('DISPUTE_ADMIN_ALERT', 'Nova Disputa para Análise'), ('SYSTEM_MESSAGE', 'Mensagem do Sistema'), ('WELCOME', 'Bem-vindo'), ('ACCOUNT_VERIFIED', 'Conta Verificada')], max_length=30, unique=True, verbose_name='Tipo de Notificação'),
        ),
    ]
